/**
 * @file io_manager.cpp
 * @brief 数据输入输出管理
 * @author pavedplaza
 * @date 2025-02-15
 *
 * 负责模拟数据的读写操作
 */

#include "phase_field_params.h"
#include "cuda_headers.h"
#include <cstdio>
#include <cstring>
#include <cstdlib>

/**
 * @brief 保存二维数组到二进制文件
 *
 * @param filename 文件名
 * @param data 数据数组
 * @param Nx x方向尺寸
 * @param Ny y方向尺寸
 * @return 成功返回true，失败返回false
 */
bool save_array_binary(const char* filename, const float* data, int Nx, int Ny) {
    FILE* fp = fopen(filename, "wb");
    if (fp == nullptr) {
        fprintf(stderr, "错误：无法打开文件 %s 进行写入\n", filename);
        return false;
    }

    size_t written = fwrite(data, sizeof(float), Nx * Ny, fp);
    fclose(fp);

    if (written != static_cast<size_t>(Nx * Ny)) {
        fprintf(stderr, "错误：写入文件 %s 失败\n", filename);
        return false;
    }

    printf("  保存数组: %s (%dx%d)\n", filename, Nx, Ny);
    return true;
}

/**
 * @brief 从二进制文件读取二维数组
 *
 * @param filename 文件名
 * @param data 数据数组（需预分配）
 * @param Nx x方向尺寸
 * @param Ny y方向尺寸
 * @return 成功返回true，失败返回false
 */
bool load_array_binary(const char* filename, float* data, int Nx, int Ny) {
    FILE* fp = fopen(filename, "rb");
    if (fp == nullptr) {
        fprintf(stderr, "错误：无法打开文件 %s 进行读取\n", filename);
        return false;
    }

    size_t read_count = fread(data, sizeof(float), Nx * Ny, fp);
    fclose(fp);

    if (read_count != static_cast<size_t>(Nx * Ny)) {
        fprintf(stderr, "错误：读取文件 %s 失败（期望%d个元素，实际读取%zu个）\n",
                filename, Nx * Ny, read_count);
        return false;
    }

    printf("  读取数组: %s (%dx%d)\n", filename, Nx, Ny);
    return true;
}

/**
 * @brief 保存数组到MATLAB格式文件（.mat）
 *
 * 保存为简单的文本格式，可以在MATLAB中直接load
 *
 * @param filename 文件名
 * @param data 数据数组
 * @param Nx x方向尺寸
 * @param Ny y方向尺寸
 * @return 成功返回true，失败返回false
 */
bool save_array_matlab(const char* filename, const float* data, int Nx, int Ny) {
    FILE* fp = fopen(filename, "w");
    if (fp == nullptr) {
        fprintf(stderr, "错误：无法打开文件 %s 进行写入\n", filename);
        return false;
    }

    // 写入MATLAB注释
    fprintf(fp, "%% Phase field data: %dx%d array\n", Ny, Nx);
    fprintf(fp, "%% Generated by PhaseFieldCUDA\n");

    // 写入数据（按列优先，MATLAB格式）
    for (int j = 0; j < Ny; j++) {
        for (int i = 0; i < Nx; i++) {
            fprintf(fp, "%.6e ", data[j * Nx + i]);
        }
        fprintf(fp, "\n");
    }

    fclose(fp);
    printf("  保存MATLAB格式: %s\n", filename);
    return true;
}

/**
 * @brief 保存模拟参数到文本文件
 *
 * @param filename 文件名
 * @param params 参数结构体
 * @return 成功返回true，失败返回false
 */
bool save_params(const char* filename, const PhaseFieldParams& params) {
    FILE* fp = fopen(filename, "w");
    if (fp == nullptr) {
        fprintf(stderr, "错误：无法打开文件 %s 进行写入\n", filename);
        return false;
    }

    fprintf(fp, "%% 相场模拟参数文件\n");
    fprintf(fp, "%% Generated by PhaseFieldCUDA\n\n");

    fprintf(fp, "%% 材料参数\n");
    fprintf(fp, "k_partition = %.6f;\n", params.k_partition);
    fprintf(fp, "epsilon_aniso = %.6f;\n", params.epsilon_aniso);
    fprintf(fp, "m_aniso = %.1f;\n", params.m_aniso);
    fprintf(fp, "omega0_aniso = %.6f;\n", params.omega0_aniso);
    fprintf(fp, "lambda_coup = %.3f;\n", params.lambda_coup);
    fprintf(fp, "D_coefficient = %.3f;\n", params.D_coefficient);
    fprintf(fp, "theta_field = %.3f;\n\n", params.theta_field);

    fprintf(fp, "%% 数值参数\n");
    fprintf(fp, "Nx = %d;\n", params.Nx);
    fprintf(fp, "Ny = %d;\n", params.Ny);
    fprintf(fp, "dx = %.6f;\n", params.dx);
    fprintf(fp, "dy = %.6f;\n", params.dy);
    fprintf(fp, "dtime = %.6f;\n", params.dtime);
    fprintf(fp, "total_time = %.3f;\n\n", params.total_time);

    fprintf(fp, "%% 边界条件\n");
    fprintf(fp, "periodic_boundary = %s;\n", params.periodic_boundary ? "true" : "false");

    fclose(fp);
    printf("  保存参数文件: %s\n", filename);
    return true;
}

/**
 * @brief 打印数组统计信息
 *
 * @param name 数组名称
 * @param data 数据数组
 * @param size 元素个数
 */
void print_array_stats(const char* name, const float* data, size_t size) {
    if (size == 0) {
        printf("%s: 空数组\n", name);
        return;
    }

    float min_val = data[0];
    float max_val = data[0];
    float sum_val = 0.0f;

    for (size_t i = 0; i < size; i++) {
        min_val = fminf(min_val, data[i]);
        max_val = fmaxf(max_val, data[i]);
        sum_val += data[i];
    }

    float mean_val = sum_val / size;

    printf("%s: min=%.6f, max=%.6f, mean=%.6f\n", name, min_val, max_val, mean_val);
}

/**
 * @brief 检查数组是否包含NaN或Inf
 *
 * @param data 数据数组
 * @param size 元素个数
 * @return 如果包含NaN或Inf返回true，否则返回false
 */
bool has_nan_or_inf(const float* data, size_t size) {
    for (size_t i = 0; i < size; i++) {
        if (isnan(data[i]) || isinf(data[i])) {
            return true;
        }
    }
    return false;
}
